### ISSUE TITLE
Proposal for a new comment syntax

### ISSUE THREAD

**Issue by thomaspeugeot** [fullstack-lang/gongdoc#84]
# Introduction

When composing comments in go, we use the same syntax as in languages such as Java, C#, C, and C++, so those familiar with those languages will not feel unfamiliar.

Consider the following example.
```go
type Triangle struct {
	Name    string
	Edges []*Point
}
type Point struct {
	Name string
        X,Y float64 
}

// Triangle implementation depends on a slice of Points via the field Triangle.Edges
```

Now, if you you refactor the struct "Point" to "Vertex" with your favorite IDE, you will notice the comment will not be refactored by the IDE: "Point" will stay "Point", not "Vertex".

Once composed, go comments are not covered by modern language tools such as refactoring, IntelliSense, code formatting, and code navigation. Additionally, comments are difficult to integrate with UML tools, which further reduces their usefulness.

This proposal tries improve the efficiency and effectiveness of writing and maintaining Go comments.

# Proposal

Experts in programming languages should consider the solution. The following are some principles from a user perspective. Below is how the new comment should like from this perspective.

```go
//go:meta
var OnTriangles = Triangle ' implementation depends on an association to a slice of 'Point 's via the field ' Triangle.Edges
```

Now, if you you refactor the struct "Point" to "Vertex", the comment is updated accordingly.

This proposal follows some principles

## The new comment is a string

The new comment is a string whose value is set at compile time and whose value can be set from identifiers. Since the new comment can reference identifiers, the compiler shall be able to convert identifiers to string at compile time.

That means the use of the '+' before and after identifiers should be averted.
Indeed, a comment is composed and read by programmers with their IDE. Therefore it should be natural to compose and read new comment and `+` are not natural for comments.

## The new comment has an identifier and is recognized as a comment by the AST

A directive shall make the the new comment visible as such in the Abstract Syntax Tree, even if the identifier is not exported or is a blank identifier. The references should be accessible in the AST.

# Relation to Unified Modeling Language

[UML standard](https://www.omg.org/spec/UML/2.5.1/PDF) standardizes comments as

`
Every kind of Element may own Comments. The owned Comments for an Element add no semantics but may represent
information useful to the reader of the model.
`

In UML, a `Note Link` may represent a relationship between a comment and an element in UML.

<img width="426" alt="Screenshot 2022-12-26 at 10 32 43" src="https://user-images.githubusercontent.com/10234087/209554330-0dabed24-d24b-4b90-bfcf-16697a8dfa57.png">

This proposal allows integration of new comments as comment with options for multiple note links from one note to elements. The referenced identifiers in the new comments are candidates for note links to UML elements.

# Workarounds

Two workarounds have been developed for an experimental UML Tool [gongdoc](https://github.com/fullstack-lang/gongdoc). gongdoc encodes the diagrams as go code. Therefore UML diagrams are refactored when the code is refactored.

The workarounds have been developed for implementing note and note links.

## Workaround 1

The first workaround use `note` for UML tools. Go offers the possibility to write [Note](https://pkg.go.dev/go/doc#Note) in comments that can be accessed by the AST. This seems not to be very popular. For instance, this is not mentioned in the [documentation](https://tip.golang.org/doc/comment) on how to write comments. 

```go
// GONGNOTE(Meta): Meta test
// This note reference Triangle and Vertex
// However, if Vertex is refactored, it will not change in the note
```
<img width="782" alt="Screenshot 2022-12-25 at 08 55 14" src="https://user-images.githubusercontent.com/10234087/209466963-3e70e8d3-8daf-4867-a123-68729bd1eaf6.png">

The note itself is referenced as a hard link in the definition of the UML diagram. 

```go
var Meta uml.Classdiagram = uml.Classdiagram{
	Classshapes: []*uml.Classshape{
		{
			ReferencedGong: &(models.Triangle{}),
			Position: &uml.Position{
				X: 25.000000,
				Y: 19.000000,
			},
[...]
	Notes: []*uml.NoteShape{
		{
			Name: `Meta`,
			Body: `Meta test
This note reference Triangle and Vertex
However, if Vertex is refactored, it will not change in the note
`,
			X:      170.000000,
			Y:      140.000000,
			Width:  240.000000,
			Heigth: 63.000000,
		},
	},
```

The note identifier is not refactorable, if the identifier of the note is changed in the code, the link is lost.

## Workaround 2

To have a  UML comment with refactorable links in go, one can implement the following 

```go
type Meta struct {
    Text string
    References []any
}

var AboutTriangles Meta{Text:"Triangle implementation depends on  Point s in the field  Triangle.Edges  of type  [3]Edge"
References: {
    Triangle{}, Point{}, Triangle{}.Edges}
```

<<insert pictures>>

This has been tested in production but it presents few limitations:

- using `Trangle{}`instead of `Triangle` feels like a non necessary hack
- this is not fun to write compared to the above proposal
- the text is not refactorable

# Implementation steps:

- [x] add example in geometry example (add Triangle and Point and test the current comment behavior with refactoring)
- [x] add parsing of Meta instance in example (this is in the gong package)
- [ ] add tree part for the Meta stuff (without links)
- [ ] implement the diagram part for Meta (for each tree node action)
- [ ] add tree part for the Meta stuff (with links)
- [ ] import diagram part (with links)
